# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase 3"
      - mvn clean compile package
      - mkdir deploy
  post_build:
    commands:
      - echo "Entered the post-build phase5"
     # - mv ./target/demo-0.0.1-SNAPSHOT.jar ./deploy
artifacts:
  files:
    - ./target/demo-0.0.1-SNAPSHOT.jar