# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - ./gradlew clean build
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv build/libs/aws-code-pipeline-0.0.1-SNAPSHOT.jar ./deploy
artifacts:
  files:
    - deploy/aws-code-pipeline-0.0.1-SNAPSHOT.jar